CP-5 Script Installer Improvements
rkbwp/LaravelInstaller pull request #2
Opened 2022-08-13 20:28 UTC by zohaibhassan156

Create .env file if not exists
Generate app key if not exists
fix assets path

2022-08-13 21:09 UTC, rkbwp requested changes

2022-08-13 21:09 UTC, rkbwp commented on src/Helpers/EnvironmentManager.php
> +        if (!file_exists($this->envPath)) {
can we please add some file permission check here?

2022-08-13 21:09 UTC, rkbwp commented on src/Providers/LaravelInstallerServiceProvider.php
> +        if (empty(config('app.key'))) {
is it possible to move this code [EnvironmentManager.php](https://github.com/ChargePanda-Organization/LaravelInstaller/pull/2/files#diff-d2602af967ed2ab1156dcd0883e0e2e788b10db8f33320943792725771275324) and recall this code right after copying the file?

2022-08-15 11:43 UTC, zohaibhassan156 commented
Update as per our discussion

2022-08-15 17:48 UTC, merged